M48
; DRILL file {KiCad 7.0.2-6a45011f42~172~ubuntu22.04.1} date Mon 19 Jun 2023 02:24:17 PM -04
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-19T14:24:17-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-6a45011f42~172~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1280
%
G90
G05
T1
X5.88Y-1.98
X5.88Y-3.2
T2
X5.8099Y-2.3398
X5.8099Y-2.8398
T0
M30
